# Form implementation generated from reading ui file 'kabinet.ui'
#
# Created by: PyQt6 UI code generator 6.4.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_kabinet(object):
    def setupUi(self, kabinet):
        kabinet.setObjectName("kabinet")
        kabinet.resize(611, 481)
        self.centralwidget = QtWidgets.QWidget(kabinet)
        self.centralwidget.setObjectName("centralwidget")
        self.exitkab = QtWidgets.QPushButton(self.centralwidget)
        self.exitkab.setGeometry(QtCore.QRect(10, 10, 75, 23))
        self.exitkab.setStyleSheet("background-color: #5555F5")
        self.exitkab.setObjectName("exitkab")
        self.stackedWidget = QtWidgets.QStackedWidget(self.centralwidget)
        self.stackedWidget.setGeometry(QtCore.QRect(30, 60, 581, 341))
        self.stackedWidget.setObjectName("stackedWidget")
        self.home = QtWidgets.QWidget()
        self.home.setObjectName("home")
        self.labelkab = QtWidgets.QLabel(self.home)
        self.labelkab.setGeometry(QtCore.QRect(60, 80, 461, 151))
        font = QtGui.QFont()
        font.setPointSize(26)
        self.labelkab.setFont(font)
        self.labelkab.setObjectName("labelkab")
        self.stackedWidget.addWidget(self.home)
        self.stats_window = QtWidgets.QWidget()
        self.stats_window.setObjectName("stats_window")
        self.stackedWidget.addWidget(self.stats_window)
        self.play_window = QtWidgets.QWidget()
        self.play_window.setObjectName("play_window")
        self.play_btn = QtWidgets.QPushButton(self.play_window)
        self.play_btn.setGeometry(QtCore.QRect(200, 140, 161, 61))
        self.play_btn.setObjectName("play_btn")
        self.stackedWidget.addWidget(self.play_window)
        self.kabplay = QtWidgets.QPushButton(self.centralwidget)
        self.kabplay.setGeometry(QtCore.QRect(70, 400, 161, 31))
        self.kabplay.setObjectName("kabplay")
        self.kabstats = QtWidgets.QPushButton(self.centralwidget)
        self.kabstats.setGeometry(QtCore.QRect(370, 400, 161, 31))
        self.kabstats.setObjectName("kabstats")
        kabinet.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(kabinet)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 611, 21))
        self.menubar.setObjectName("menubar")
        kabinet.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(kabinet)
        self.statusbar.setObjectName("statusbar")
        kabinet.setStatusBar(self.statusbar)

        self.retranslateUi(kabinet)
        QtCore.QMetaObject.connectSlotsByName(kabinet)

    def retranslateUi(self, kabinet):
        _translate = QtCore.QCoreApplication.translate
        kabinet.setWindowTitle(_translate("kabinet", "Личный кабинет"))
        self.exitkab.setText(_translate("kabinet", "Выйти"))
        self.labelkab.setText(_translate("kabinet", "Выберите нужное вам окно"))
        self.play_btn.setText(_translate("kabinet", "Сыграть"))
        self.kabplay.setText(_translate("kabinet", "Окно партии"))
        self.kabstats.setText(_translate("kabinet", "Окно статистики"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    kabinet = QtWidgets.QMainWindow()
    ui = Ui_kabinet()
    ui.setupUi(kabinet)
    kabinet.show()
    sys.exit(app.exec())
