# Form implementation generated from reading ui file 'login.ui'
#
# Created by: PyQt6 UI code generator 6.4.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_authorization(object):
    def setupUi(self, authorization):
        authorization.setObjectName("authorization")
        authorization.resize(489, 419)
        self.centralwidget = QtWidgets.QWidget(authorization)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, 70, 231, 51))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(0, 120, 231, 51))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.loginbtn = QtWidgets.QPushButton(self.centralwidget)
        self.loginbtn.setGeometry(QtCore.QRect(160, 270, 141, 71))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.loginbtn.setFont(font)
        self.loginbtn.setObjectName("loginbtn")
        self.input_login = QtWidgets.QLineEdit(self.centralwidget)
        self.input_login.setGeometry(QtCore.QRect(180, 80, 231, 41))
        self.input_login.setObjectName("input_login")
        self.input_password = QtWidgets.QLineEdit(self.centralwidget)
        self.input_password.setGeometry(QtCore.QRect(180, 130, 231, 41))
        self.input_password.setObjectName("input_password")
        authorization.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(authorization)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 489, 21))
        self.menubar.setObjectName("menubar")
        authorization.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(authorization)
        self.statusbar.setObjectName("statusbar")
        authorization.setStatusBar(self.statusbar)

        self.retranslateUi(authorization)
        QtCore.QMetaObject.connectSlotsByName(authorization)

    def gettext(self):
        return self.input_login.text()

    def retranslateUi(self, authorization):
        _translate = QtCore.QCoreApplication.translate
        authorization.setWindowTitle(_translate("authorization", "Окно авторизации"))
        self.label.setText(_translate("authorization", "Введите логин:"))
        self.label_2.setText(_translate("authorization", "Введите пароль:"))
        self.loginbtn.setText(_translate("authorization", "OK"))


